--phantom reads part 1
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	SELECT * FROM Student WHERE age BETWEEN 18 and 21
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Student WHERE age BETWEEN 18 and 21
COMMIT TRAN